# Generated by Django 3.2.14 on 2022-07-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('jop_type', models.CharField(choices=[('FULL TIME', 'FULL TIME'), ('PART TIME', 'PART TIME')], max_length=20)),
                ('puplishat', models.DateTimeField(auto_now=True)),
                ('salary', models.IntegerField(default=1)),
                ('experiance', models.IntegerField(default=5)),
                ('vecancy', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
