# Generated by Django 3.2.14 on 2022-07-06 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='categori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.categoryies'),
            preserve_default=False,
        ),
    ]
