# Generated by Django 3.2.14 on 2022-07-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_categori'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=1, upload_to='jobs'),
            preserve_default=False,
        ),
    ]
